# Generated by Django 3.2.7 on 2021-12-15 17:58

import computed_property.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingrequest',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='processingrequest',
            name='dicing_request',
        ),
        migrations.RemoveField(
            model_name='processingrequest',
            name='grind_request',
        ),
        migrations.AddField(
            model_name='processingrequest',
            name='fully_filled',
            field=computed_property.fields.ComputedBooleanField(compute_from='is_fully_filled', default=False, editable=False),
        ),
    ]
