# Generated by Django 3.2.7 on 2021-12-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processing_requests', '0002_auto_20211215_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingrequest',
            name='fully_filled',
        ),
        migrations.AddField(
            model_name='processingrequest',
            name='report',
            field=models.TextField(blank=True, null=True, verbose_name='Report'),
        ),
    ]
