# Generated by Django 3.2.7 on 2021-12-13 21:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_date', models.DateField(blank=True, null=True, verbose_name='Process Deadline')),
                ('report_input', models.TextField(null=True)),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity of Wafers')),
                ('company_name', models.ManyToManyField(to='company.Customer', verbose_name='Company')),
                ('engineer_PIC', models.ManyToManyField(blank=True, to='company.Engineer')),
                ('material_1', models.ManyToManyField(related_name='material_report', to='company.WaferMaterial', verbose_name='Material')),
            ],
            managers=[
                ('reports', django.db.models.manager.Manager()),
            ],
        ),
    ]
