# Generated by Django 3.2.7 on 2021-12-13 21:17

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BondMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bond_material', models.CharField(max_length=150, verbose_name='Bond Material')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='Company Name')),
                ('address', models.CharField(max_length=300, verbose_name='Shipping Address')),
            ],
            managers=[
                ('customers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('employee_number', models.CharField(max_length=6, verbose_name='Employee Number')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
            ],
        ),
        migrations.CreateModel(
            name='Tape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tape_spec', models.CharField(max_length=50, verbose_name='Full Tape Spec')),
                ('tape_THK', models.IntegerField(verbose_name='Tape Thickness')),
                ('base_film', models.CharField(blank=True, max_length=50, verbose_name='Base Film')),
                ('base_THK', models.IntegerField(blank=True, default=0, null=True, verbose_name='Base Film Thickness')),
                ('adhesive_film', models.CharField(blank=True, max_length=50, verbose_name='Adhesive Film')),
                ('adhesive_THK', models.IntegerField(blank=True, default=0, null=True, verbose_name='Adhesive Film Thickness')),
                ('adhesive_strength', models.IntegerField(blank=True, default=0, null=True, verbose_name='Adhesive Film Strength')),
            ],
        ),
        migrations.CreateModel(
            name='WaferMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wafer_material', models.CharField(max_length=150, verbose_name='Wafer Material')),
            ],
        ),
        migrations.CreateModel(
            name='WaferShape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wafer_shape', models.CharField(max_length=150, verbose_name='Wafer Shape')),
            ],
        ),
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_spec', models.CharField(max_length=30, verbose_name='Full Wheel Spec')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='Wheel Code')),
                ('size_spec', models.CharField(blank=True, max_length=20, verbose_name='Full Size Spec')),
                ('lot_number', models.CharField(max_length=20, verbose_name='Lot Number')),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.employee')),
                ('speciality', models.TextField(blank=True, max_length=100, verbose_name='Engineering Speciality')),
            ],
            bases=('company.employee',),
        ),
        migrations.CreateModel(
            name='GrindWheel',
            fields=[
                ('wheel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.wheel')),
            ],
            bases=('company.wheel',),
        ),
        migrations.CreateModel(
            name='PolishWheel',
            fields=[
                ('wheel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.wheel')),
            ],
            bases=('company.wheel',),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('employee_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='company.employee')),
            ],
            bases=('company.employee',),
        ),
    ]
